apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: armstrong02
  labels:
    kubernetes.io/service-name: armstrong02
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - "172.30.240.1"